### ISSUE TITLE
"update" option md5 issue

### ISSUE THREAD

**Issue by jkychn** [ttgapers/cakeqos-merlin#12]
```
KBvUTgSItSQdjpCB@RT-AC86U-87E8:/tmp/home/root# /jffs/scripts/cake-qos update ac86u
/jffs/scripts/cake-qos: line 331: #!/bin/sh: not found
CakeQOS-Merlin v0.0.5: Local and server md5 don't match, updating...

CakeQOS-Merlin v0.0.5: Your cake binaries are up-to-date.

KBvUTgSItSQdjpCB@RT-AC86U-87E8:/tmp/home/root# /jffs/scripts/cake-qos update ac86u
/jffs/scripts/cake-qos: line 331: #!/bin/sh: not found
CakeQOS-Merlin v0.0.5: Local and server md5 don't match, updating...

CakeQOS-Merlin v0.0.5: Your cake binaries are up-to-date.
```

**Comment by jkychn** [comment]
@maghuro if you could please look into this. Thank you :)

**Comment by jkychn** [comment]
Just received an update: `It fixed itself when i ran update check again`

If you could confirm this isn't an issue feel free to close this. Thanks!

**Comment by maghuro** [comment]
Maybe it's because you're putting the model in front. Don't need it 

I can only go to my PC and debug everything I've commited this night

**Comment by maghuro** [comment]
@ttgapers can you please give me write access? so I can pull directly to develop?

**Comment by ttgapers** [comment]
> 
> 
> @ttgapers can you please give me write access? so I can pull directly to develop?

Done I thought I did it already. Let me know if you have issues @maghuro

**Comment by maghuro** [comment]
> > @ttgapers can you please give me write access? so I can pull directly to develop?
> 
> Done I thought I did it already. Let me know if you have issues @maghuro

I don't have write access yet...

**Comment by maghuro** [comment]
oh i had to accept the invite! :) :P

**Comment by maghuro** [comment]
Fixed: https://github.com/ttgapers/cakeqos-merlin/commit/f6b7ed8c7b95a5baaad5298b4bee97bf5089513e
