### ISSUE TITLE
Start if line present

### ISSUE THREAD

**Issue by maghuro** [ttgapers/cakeqos-merlin#31]
@JackYaz
I need your expertise.

Everytime we use option "stop", the cake stops and the start line on nat-start keeps untouched. That's the correct way!

However, when pressing start, we have to introduce the values again.

My suggestion is, if possible, change the option "stop" to "toggle"

When opening the menu, the menu would check if cake is running or not and stick this info above the menu. Then the toggle button would do it's job (stop if running and start if stopped).

However, if one presses toggle and the start line is on the nat-start, it'll use that line with that params to start cake.
If it isn't present on nat-start, then the script would ask for all the parameters needed.

Note that the option 1 (start) should always ask for parameters. In fact it could be renamed to enabled/configure or whatsoever.

Did I made me understand? 😊

Thanks.

**Comment by jackyaz** [comment]
Sure, I can do that but it will be sometime tomorrow

**Comment by ttgapers** [comment]
@jackyaz thanks for all your help on this thus far! If it's easier I can make you send you a contributor invite...

**Comment by ttgapers** [comment]
@jackyaz thanks for helping out on this project!

**Comment by Adamm00** [comment]
This has been addressed in a future update.

**Comment by maghuro** [comment]
Fixed.
