### ISSUE TITLE
cake-qos start not changing nat-start

### ISSUE THREAD

**Issue by ttgapers** [ttgapers/cakeqos-merlin#33]
Let's see if I am doing something wrong, but looks like cake-qos start up down "additional parameters" doesn't change diffserv4 to besteffort etc.

If I uninstall and issue the start command after pulling the script down again, all is well. I'll have a look at the code, but I know I am playing catch up.

Confirmed. If I issue stop command and the start with a different parameter it starts correctly but doesn't touch/edit **nat-start**.

**Comment by ttgapers** [comment]
Looks like update should do it..will verify and close.

**Comment by jkychn** [comment]
Probably related to this line: https://github.com/ttgapers/cakeqos-merlin/blob/master/cake-qos.sh#L202

What does running `grep -qF "# CakeQOS-Merlin" /jffs/scripts/nat-start` in terminal return?

**Comment by Adamm00** [comment]
I have addressed this (and other issues) in my local fork, so hold tight until its ready to go live.

**Comment by maghuro** [comment]
Can you check it's working now with #34 ?

**Comment by maghuro** [comment]
Tested. Fixed
