### ISSUE TITLE
Sed command

### ISSUE THREAD

**Issue by maghuro** [ttgapers/cakeqos-merlin#35]
I'm not good with sed, can someone check:
https://github.com/ttgapers/cakeqos-merlin/blob/develop/cake-qos.sh#L234

I want to remove the entries from nat-start and services stop upon "Stop Cake"

**Comment by Adamm00** [comment]
Wont work as vars don't expand when using single quotes '', you can just use the plaintext version;

`sed -i '\~# CakeQOS-Merlin~d' /jffs/scripts/nat-start /jffs/scripts/services-stop`

**Comment by maghuro** [comment]
Thanks Adamm!
