### ISSUE TITLE
TravisCI intergration

### ISSUE THREAD

**Issue by Adamm00** [ttgapers/cakeqos-merlin#39]
TravisCI essentially runs shellcheck on the repo every time a commit is pushed (which is the checkmarks you can see on other repos). The configuration file is already present, @ttgapers just needs to enable the feature as he is the repo owner.

**Comment by ttgapers** [comment]
Let me check that @Adamm00

**Comment by maghuro** [comment]
have you deleted develop branch?

**Comment by ttgapers** [comment]
> 
> 
> have you deleted develop branch?

Not me, but I believe @Adamm00 and they are working on this more than myself. Please confirm here...and if necessary you all can decide on when/if to push the next release...still shows 0.1.0...

**Comment by maghuro** [comment]
ho you can push it now!

**Comment by maghuro** [comment]
TravisCI implemented
