### ISSUE TITLE
Does Flow Cache need to be disabled

### ISSUE THREAD

**Issue by Adamm00** [ttgapers/cakeqos-merlin#40]
I am not sure on this myself, I know regular Asus QOS disables Runner but leaves Flow Cache enabled, are the requirements different for Cake?

**Comment by ttgapers** [comment]
That I am not sure @Adamm00 but can research and get back to us here...

**Comment by ttgapers** [comment]
@Adamm00 I have not found anything definitive on this. Would this be something we can test on our own in your opinion?

**Comment by ttgapers** [comment]
See: https://www.snbforums.com/threads/release-cakeqos-merlin.64800/page-26#post-597296

Cake: Runner and Flow Cache disabled
