### ISSUE TITLE
/opt/bin

### ISSUE THREAD

**Issue by maghuro** [ttgapers/cakeqos-merlin#45]
After the script refactoring, /opt/bin link is missing after a fresh install.

**Comment by Adamm00** [comment]
Can't reproduce;

`skynet@RT-AX88U-DC28:/tmp/mnt/USB/entware/bin# cake-qos uninstall

#########################################################
##               _                                     ##
##              | |                                    ##
##    ___  __ _ | | __ ___          __ _   ___   ___   ##
##   / __|/ _` || |/ // _ \ ______ / _` | / _ \ / __|  ##
##  | (__ |(_| ||   <|  __/|______| (_| || (_) |\__ \  ##
##   \___|\__,_||_|\_\\___|        \__, | \___/ |___/  ##
##                                    | |              ##
##                                    |_|              ##
##                                                     ##
##      https://github.com/ttgapers/cakeqos-merlin     ##
##                        v1.0.1                       ##
##                                                     ##
#########################################################


#########################################################

CakeQOS-Merlin: Stopping
Broadcom Packet Flow Cache HW acceleration <ENABLED>
CPU Speed (*) ==> Enable
Changing power settings. Setting cpu frequency setting to adaptive.
Broadcom Packet Flow Cache learning via BLOG enabled.
Removing package sched-cake-oot from root...
Removing package tc-adv from root...
libnl-tiny was autoinstalled and is now orphaned, removing.
Removing package libnl-tiny from root...
libcap was autoinstalled and is now orphaned, removing.
Removing package libcap from root...
libelf was autoinstalled and is now orphaned, removing.
Removing package libelf from root...
libintl-full was autoinstalled and is now orphaned, removing.
Removing package libintl-full from root...
libmnl was autoinstalled and is now orphaned, removing.
Removing package libmnl from root...

skynet@RT-AX88U-DC28:/tmp/mnt/USB/entware/bin# ls /opt/bin
ash               column            diversion         entware-services  find              grep              localedef.new     opkg              sh                vpnflix
base64            dig               egrep             fgrep             firewall          locale.new        netstat           pixelserv-tls     sqlite3           xargs
skynet@RT-AX88U-DC28:/tmp/mnt/USB/entware/bin# mkdir -p /jffs/addons/cake-qos && /usr/sbin/curl -s "https://raw.githubusercontent.com/ttgapers/cakeqos-merlin/master/cake-qos.sh" -o "/jffs/addons/cake-qos/cake-qos" && chmod 755 /jffs/addons/cake-qos/cake-qos && sh /jffs/
addons/cake-qos/cake-qos install

#########################################################
##               _                                     ##
##              | |                                    ##
##    ___  __ _ | | __ ___          __ _   ___   ___   ##
##   / __|/ _` || |/ // _ \ ______ / _` | / _ \ / __|  ##
##  | (__ |(_| ||   <|  __/|______| (_| || (_) |\__ \  ##
##   \___|\__,_||_|\_\\___|        \__, | \___/ |___/  ##
##                                    | |              ##
##                                    |_|              ##
##                                                     ##
##      https://github.com/ttgapers/cakeqos-merlin     ##
##                        v1.0.1                       ##
##                                                     ##
#########################################################


#########################################################

Downloading http://bin.entware.net/aarch64-k3.10/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/entware
CakeQOS-Merlin: Updated sched-cake-oot_2020-05-28-a5dccfd8-ax_aarch64-3.10.ipk
No packages removed.
Installing sched-cake-oot (2020-05-28-a5dccfd8-ax) to root...
Configuring sched-cake-oot.
CakeQOS-Merlin: Updated tc-adv_4.16.0-git-20191110_aarch64-3.10.ipk
No packages removed.
Installing tc-adv (4.16.0-git-20191110) to root...
Installing libnl-tiny (2019-10-29-0219008c-1) to root...
Downloading http://bin.entware.net/aarch64-k3.10/libnl-tiny_2019-10-29-0219008c-1_aarch64-3.10.ipk
Installing libcap (2.33-2) to root...
Downloading http://bin.entware.net/aarch64-k3.10/libcap_2.33-2_aarch64-3.10.ipk
Installing libintl-full (0.19.8.1-2) to root...
Downloading http://bin.entware.net/aarch64-k3.10/libintl-full_0.19.8.1-2_aarch64-3.10.ipk
Installing libelf (0.179-1) to root...
Downloading http://bin.entware.net/aarch64-k3.10/libelf_0.179-1_aarch64-3.10.ipk
Installing libmnl (1.0.4-2) to root...
Downloading http://bin.entware.net/aarch64-k3.10/libmnl_1.0.4-2_aarch64-3.10.ipk
Configuring libcap.
Configuring libmnl.
Configuring libintl-full.
Configuring libnl-tiny.
Configuring libelf.
Configuring tc-adv.

#########################################################


Please enter your download speed:

[Mbit]: 92


Please enter your upload speed:

[Mbit]: 37


Select Queue Priority Type:
[1]  --> besteffort (default)
[2]  --> diffserv3
[3]  --> diffserv4
[4]  --> diffserv8

[1-4]: 1


Please enter your extra options:
[Options]: ethernet ack-filter


#########################################################

CakeQOS-Merlin: Starting - ( 92Mbit | 37Mbit | besteffort | ethernet ack-filter )
Broadcom Packet Flow Cache HW acceleration <DISABLED>
CPU Speed (*) ==> Disable
Changing power settings. Forcing cpu to max frequency.
   Set cpuspeed to on(pwr config --cpuspeed on) to make it adaptive again
Broadcom Packet Flow Cache learning via BLOG disabled.
Broadcom Packet Flow Cache flushing the flows

#########################################################

skynet@RT-AX88U-DC28:/tmp/mnt/USB/entware/bin# ls /opt/bin
ash               cake-qos          dig               egrep             fgrep             firewall          locale.new        netstat           pixelserv-tls     sqlite3           xargs
base64            column            diversion         entware-services  find              grep              localedef.new     opkg              sh                vpnflix
skynet@RT-AX88U-DC28:/tmp/mnt/USB/entware/bin#
`
