### ISSUE TITLE
standard name

### ISSUE THREAD

**Issue by maghuro** [ttgapers/cakeqos-merlin#48]
Please consider using of **cakeqos** instead of **cake-qos** on symlink.

Easier to write and standard.

Don't need to write something to remove the "-" one, it will disappear on reboot. Just remove the hyphen.

**Comment by Adamm00** [comment]
You can use tab in most SSH clients to autocomplete, after three letters the shell does the work for you. Very much too late now to change the name of the project or introduce inconsistencies where the script is named cake-qos.sh but the executable is cakeqos. Keep it simple.
