### ISSUE TITLE
line 725: syntax error: unexpected word (expecting ")")

### ISSUE THREAD

**Issue by npmstart-pray** [ttgapers/cakeqos-merlin#53]
as noted 
[<a href="https://www.snbforums.com/threads/release-cakeqos-merlin.64800/page-40#post-599161">[Release] CakeQOS-Merlin</a>](url)
and requested.

Happy Canada Day.  The Lancaster just flew over a few minutes ago, sounding fierce.

**Comment by Adamm00** [comment]
This is the same issue I was trying to describe in #44 (which I am now able to reproduce) . I will switch back to a hard exit for the time being.
