### ISSUE TITLE
Implement presets function

### ISSUE THREAD

**Issue by rgnldo** [ttgapers/cakeqos-merlin#55]
Important function for lay users, the function with predefined options with unlimited, rate DL / UP = 0, based on connectivity (DOCIS, VDSL etc)

**Comment by Adamm00** [comment]
Presets are subject to opinion, information like this is best saved for a readme or installation thread. Even using the unlimited option is subject to debate, there's just too many combinations to keep everyone satisfied.

**Comment by rgnldo** [comment]
Correct. I thought in this way. We must find patterns of consensus,
