### ISSUE TITLE
AX58U No Internet

### ISSUE THREAD

**Issue by coffeevotary** [ttgapers/cakeqos-merlin#66]
Install AX58U via Entware works
When enabling Cake-QOS, all internet traffic is stopped. LAN traffic works.  Any setting within Cake-QOS, no go. 

No error message found in system logs.
To re-enable internet, must uninstall Cake-QOS and restart router.

**Comment by ghost-420** [comment]
I have the same issue on the AX58U running Merlin 386.1_beta3 and CakeQOS-Merlin 1.0.7.
Might edit later if I find any new logs after I test again.

**Comment by jata1** [comment]
I have the same issue with cake but only with 386.1 (b5)

**Comment by ttgapers** [comment]
> 
> 
> Install AX58U via Entware works
> When enabling Cake-QOS, all internet traffic is stopped. LAN traffic works. Any setting within Cake-QOS, no go.
> 
> No error message found in system logs.
> To re-enable internet, must uninstall Cake-QOS and restart router.
