### ISSUE TITLE
Curl timeout is too short

### ISSUE THREAD

**Issue by shemminger** [ttgapers/cakeqos-merlin#70]
I could not get cake-qos to install.
It turned out the default timeout of 3 seconds was too small and the  version file (and others) would not download.
The workaround was to globally remove connect-timeout.

Please fix.

**Comment by ttgapers** [comment]
First time I've seen this one from a user. Was this your first time using/installing cake-qos? I'm wondering if it could be a transient issue.

**Comment by shemminger** [comment]
Yes this was initial download. Could just be the github server being slow/overloaded.
