### ISSUE TITLE
any statistics available

### ISSUE THREAD

**Issue by dtaht** [ttgapers/cakeqos-merlin#81]
I was pleased to learn of this project today. Do your users have any visibility into any of the statistics cake keeps? I am primarily interested in backlog, drops, ack drops, and marks, but there are a variety of others.

By which I meant graphs, over time.

**Comment by underd0se** [comment]
@dtaht I'm a user of this project and yes, we have access to stats in the router GUI as well as to configuration and status information.  

![image](https://user-images.githubusercontent.com/16015932/143288954-c6b4b8c1-060e-4c08-a99f-ec2be35545b6.png)

**Comment by ttgapers** [comment]
@dtaht thanks for  your comments/question. Appreciate it.

On the graphing etc., I believe this is something @dave14305 has been toying with for the future. @dave14305  would be better placed to comment on if/when/how that might be happening.

**Comment by dtaht** [comment]
My overall campaign is to try and inform more users as to te value of dropping packets intelligently, and to do some a/b testing to pass the good word along. 

in your example above you might want to turn on the ack-filter on the upload. 

It would be good if the cake community could all agree on the right rules for re-marking videoconferencing traffic. 

I am also always curious as to what applications are using ecn, also. 

and seeing *live* stats, with a backlog, and happy users always is nice. thx for doing this port!

**Comment by dave14305** [comment]
> @dtaht thanks for your comments/question. Appreciate it.
> 
> On the graphing etc., I believe this is something @dave14305 has been toying with for the future. @dave14305 would be better placed to comment on if/when/how that might be happening.

I’ve been using OpenWrt and digging into the multiple QoS/SQM efforts there (e.g. qosify, adapting QoS rules to nftables, etc.).

The big question was always, “What’s interesting in the CAKE stats output?” We have some feedback now from @dtaht to answer that question.

However I’m not sure if I’ll be switching back to Merlin firmware in the near future to work on this Addon.

**Comment by dtaht** [comment]
Dream:

packets, ack-drops, drops, marks, on a log scale on one graph
backlog in bytes for each tin, linear scale on another graph
peak delay for each tin (also one graph), linear

there has been a variety of attempts to get there out there...

**Comment by dave14305** [comment]
> packets, ack-drops, drops, marks, on a log scale on one graph
This is where it could be sloppy if we're dealing with 4 metrics for 1 to 8 tins (hopefully no one really uses diffserv8).
