### ISSUE TITLE
AC88U Support

### ISSUE THREAD

**Issue by KaMiKaZeE1221** [ttgapers/cakeqos-merlin#89]
Any chance of getting support for the AC88U, I know it's only a dual core but I'm only running a 100/40 connection.
or if anyone knows how to install it on the AC88U please let me know :)

**Comment by ttgapers** [comment]
Versions prior to 386.2 are supported on the legacy 386 branch or 384 branch. This script will automatically install the appropriate legacy version if your firmware does not support Cake natively.

**Comment by KaMiKaZeE1221** [comment]
> Versions prior to 386.2 are supported on the legacy 386 branch or 384 branch. This script will automatically install the appropriate legacy version if your firmware does not support Cake natively.

I only asked because I get this error, and that's on the 386 branch, but all good, thanks for replying anyway 🙂

![raw](https://github.com/user-attachments/assets/e7cfc01c-82a5-4a91-bc9f-dd36b840e176)
